### ISSUE TITLE
Not being engaged under https://resource.example.com/jira/browse/TODO-33

### ISSUE THREAD

**Issue by nathanbrauer** [GreyRook/harvest-jira-chrome#1]
Works here:
![image](https://cloud.githubusercontent.com/assets/323945/23680768/466aac8e-0341-11e7-8e13-ef277fe1a064.png)

Not here:
![image](https://cloud.githubusercontent.com/assets/323945/23680748/33076c18-0341-11e7-9ad8-80c18da57452.png)

**Comment by nathanbrauer** [comment]
Let me know how I can help!

**Comment by itsbjoern** [comment]
Strange to see that it doesn't load at all.
Does the problem only occur on /browse on the marketo page? Does it load/display in the /projects view?

**Comment by nathanbrauer** [comment]
I don't think so. I'll double check...

**Comment by nathanbrauer** [comment]
Same problem:
![image](https://cloud.githubusercontent.com/assets/323945/23779058/d7093104-04f2-11e7-88c0-5bf2f9e254ff.png)

**Comment by FlorianLudwig** [comment]
Root cause seems to be the marketo installation is in the subroute `/jira` and not directly on `/`

**Comment by FlorianLudwig** [comment]
@BFriedrichs 

please also check for `<meta name="application-name" content="JIRA">`

**Comment by itsbjoern** [comment]
The issue is fixed via 23341e8b094590fc4804e54a8675975137aeef42
The updated version should now also be available in the google web store.

**Comment by FlorianLudwig** [comment]
@nathanbrauer Please check if this resolves the issue for you.

**Comment by nathanbrauer** [comment]
BALLER!  Thanks, @BFriedrichs & @FlorianLudwig!  Confirmed it's working!
