### ISSUE TITLE
Chrome store version outdated

### ISSUE THREAD

**Issue by kmwalsh** [GreyRook/harvest-jira-chrome#15]
Hello, thanks for your extension that has saved many hours.

* [Chrome store](https://chrome.google.com/webstore/detail/jira-harvest-time-trackin/klgljijecjfkdfobihclllkadmoeokgg/) lists the version at 2.4.
* The repo and releases here list the version at 3.0.0.

Are there plans to put the 3.0.0 version onto Chrome Store?

On the 2.4 version we're currently experiencing an issue on Board view where no tickets are loading in. When we install manually from Github, the board view issue goes away. It would be sweet to get the 3.0.0 version into Chrome store and avoid the "non-store" extension installation.

Additional note, getting a warning in the Chrome extension panel about manifest.json versioning. "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details." Still works at this point but seems it may stop working at some point in the near future.

Thank you.

**Comment by vdbongard** [comment]
We will have a look into updating the extension.

**Comment by vdbongard** [comment]
The extension is updated to version 4.0.0 and it does support the new Manifest v3 now. It is in review in the Chrome Web Store and will be available there soon.

**Comment by kmwalsh** [comment]
Thank you! Most excellent. Appreciate your time and effort on this very much.
