### ISSUE TITLE
Add the tracking button on the Board Detail View

### ISSUE THREAD

**Issue by FabianElsmer** [GreyRook/harvest-jira-chrome#3]
![screenshot from 2017-06-21 19-33-15](https://user-images.githubusercontent.com/9722121/27398100-fce2785a-56b8-11e7-8255-e3f69d70b17b.png)

The details of a ticket open as a sidebar to the board, I would really like to directly start tracking from this view instead of having to go to each tasks page to start or switch the tracking.

**Comment by itsbjoern** [comment]
Added via 3d3c735d9c50002daf8982b069f634a34854b4b4
