### ISSUE TITLE
Adding issue id to task notes

### ISSUE THREAD

**Issue by vdenisov** [GreyRook/harvest-jira-chrome#4]
I wonder if it would be possible to add issue id to the note text, so it would look something like this
```
EN-10023: Fix failing request to ...
```
instead of just
```
Fix failing request to...
```
?

**Comment by FlorianLudwig** [comment]
Hi @vdenisov ,

Seems like a good idea to me.  Not sure if we should have this configurable or not.  I think it's fine without configuration.

Would you be interested in implementing it?

**Comment by vdenisov** [comment]
Hmm, I've never developed Chrome extensions, but that shouldn't be that difficult... Let me check it out and I'll get back to you in a couple of days.

**Comment by itsbjoern** [comment]
Changing 
https://github.com/GreyRook/harvest-jira-chrome/blob/9d4242632ac056df334bffdbd4e8192a39185eaf/extension/jiraharvest.js#L52-L55

to

```
var key = JIRA.Issue.getIssueKey();
harvestItem = {
    'id': key,
    'name': '[' + key + '] ' + issueTitle,
};
```
probably should do the trick, untested.

**Comment by FlorianLudwig** [comment]
@vdenisov I just published an update to the chrome store - it should update soon with your feature request included.
